#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "readarr"
name = "Readarr"
description.en = "Book Manager and Automation (Sonarr for Ebooks)"
description.fr = "Gestionnaire de livres et automatisation (Sonarr pour livres électroniques)"

version = "0.3.6.2232~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://wiki.servarr.com/readarr/installation/linux"
code = "https://github.com/Readarr/Readarr"
fund = "https://readarr.com/donate"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/readarr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Readarr/Readarr/releases/download/v0.3.6.2232/Readarr.develop.0.3.6.2232.linux-core-x64.tar.gz"
        sha256 = "1f8f168ea4401bb23e20f84200db89d77ec8c025e44dae6fadf8795a6e2d3b21"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"
    api.auth_header = false

    [resources.ports]
    main.default = 8787

    [resources.apt]
    packages = "sqlite3, curl"
