#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "readarr"
name = "Readarr"
description.en = "Book Manager and Automation (Sonarr for Ebooks)"
description.fr = "Gestionnaire de livres et automatisation (Sonarr pour livres électroniques)"

version = "0.3.19.2437~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://readarr.com/"
admindoc = "https://wiki.servarr.com/readarr/installation/linux"
code = "https://github.com/Readarr/Readarr"
fund = "https://opencollective.com/readarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/readarr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Readarr/Readarr/releases/download/v0.3.19.2437/Readarr.develop.0.3.19.2437.linux-core-x64.tar.gz"
        sha256 = "b8d6508b3bce3f280ff8b5720401ac84171f8c2e2bad7f661ad6aabfca4158a0"

        # autoupdater disabled as we're using pre releases
        # autoupdate.strategy = "latest_github_tag"
        # autoupdate.asset = "^Readarr.develop.*linux-core-x64.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 8787

    [resources.apt]
    packages = "sqlite3, curl"
